Repository sarulab-speech/UTMOSv2, pull requests merged in 2025-02, with the labels that each got.

#41 Remove ckpt
  models/fusion_stage3/fold0_s42_best_model.pth
  models/fusion_stage3/fold1_s42_best_model.pth
  models/fusion_stage3/fold2_s42_best_model.pth
  models/fusion_stage3/fold3_s42_best_model.pth
  models/fusion_stage3/fold4_s42_best_model.pth
  utmosv2/_core/create.py
  utmosv2/dataset/_utils.py
  utmosv2/runner/_train.py
  utmosv2/utils/_constants.py
  utmosv2/utils/_download.py
  utmosv2/utils/_task_dependents/initializers.py
Labels: enhancement

#43 Update VSCode settings
  .vscode/settings.json
Labels: chore

#42 Add config type
  utmosv2/_settings/_config.py
  utmosv2/dataset/_base.py
  utmosv2/dataset/_utils.py
  utmosv2/dataset/multi_spec.py
  utmosv2/dataset/ssl_multispec.py
  utmosv2/model/multi_spec.py
  utmosv2/model/ssl.py
  utmosv2/model/ssl_multispec.py
  utmosv2/preprocess/_preprocess.py
  utmosv2/runner/_inference.py
  utmosv2/runner/_train.py
  utmosv2/utils/_pure/initializers.py
  utmosv2/utils/_pure/save.py
  utmosv2/utils/_pure/split.py
  utmosv2/utils/_task_dependents/initializers.py
  utmosv2/utils/_task_dependents/save.py
Labels: refactor

#44 Update README and remove `.gitattributes`
  .gitattributes
  README.md
Labels: documentation

#45 Set `disallow_untyped_defs=true` and add missing type annotations
  inference.py
  pyproject.toml
  train.py
  utmosv2/_core/create.py
  utmosv2/_core/model/_common.py
  utmosv2/_core/model/_models.py
  utmosv2/_settings/_config.py
  utmosv2/dataset/_base.py
  utmosv2/dataset/_utils.py
  utmosv2/dataset/multi_spec.py
  utmosv2/dataset/ssl.py
  utmosv2/dataset/ssl_multispec.py
  utmosv2/model/multi_spec.py
  utmosv2/model/ssl.py
  utmosv2/model/ssl_multispec.py
  utmosv2/preprocess/_preprocess.py
  utmosv2/utils/_pure/metrics.py
  utmosv2/utils/_pure/save.py
  utmosv2/utils/_task_dependents/initializers.py
  utmosv2/utils/_task_dependents/log.py
  utmosv2/utils/_task_dependents/save.py
Labels: code-fix

#47 Remove unused save utils
  utmosv2/utils/_task_dependents/initializers.py
Labels: code-fix

#49 Add tests
  .github/workflows/tests.yml
  pyproject.toml
  tests/core_tests/test_create.py
  utmosv2/_core/create.py
  utmosv2/_settings/_config.py
  utmosv2/model/ssl_multispec.py
Labels: bug, code-fix

#50 Update torch installation for the CPU-only version in CI
  .github/workflows/mypy_check.yml
  .github/workflows/tests.yml
Labels: ci

#51 Bump up to v1.1.0
  utmosv2/__init__.py
Labels: version
